[alias]
txtx-install = "install --path crates/txtx-cli --features supervisor_ui --locked --force"
test-validation-core = "test --no-default-features --package txtx-core --lib validation::hcl_validator::tests"
test-validation-utils = "test --no-default-features --package txtx-test-utils"
test-validation-all = "test --no-default-features --lib --tests --package txtx-core --package txtx-test-utils"

test-lint-unit = "test --package txtx-cli --bin txtx --no-default-features --features cli cli::lint::"
test-lint-int = "test --package txtx-cli --test linter_tests_builder --no-default-features --features cli"
test-lint-all = "test --package txtx-cli --no-default-features --features cli"

[build]
rustflags = ["--cfg", "tokio_unstable"]
